name = "cybercode230/aiken-cardano"
version = "0.0.0"
compiler = "v1.1.19"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'cybercode230/aiken-cardano'"

[repository]
user = "cybercode230"
project = "aiken-cardano"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.5.0"
source = "github"

[config]

